### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by fubel** [GehenHe/TRACTA#1]
Hello,

I enjoyed reading your paper. Do you plan to release the code for TRACTA in this repository as well?

**Comment by zchoi** [comment]
> Hello,
> 
> I enjoyed reading your paper. Do you plan to release the code for TRACTA in this repository as well?

dude do you get the code? I also wanna to study some details about code.

**Comment by fubel** [comment]
> > Hello,
> > I enjoyed reading your paper. Do you plan to release the code for TRACTA in this repository as well?
> 
> dude do you get the code? I also wanna to study some details about code.

No I haven't got it.

**Comment by GehenHe** [comment]
Hi, our code has already been deployed for commercial use, thus it was not allowed to be distributed. 
However, we will check whether it is possible to release the codes of our key algorithms.

**Comment by abnercloud** [comment]
> Hi, our code has already been deployed for commercial use, thus it was not allowed to be distributed.
> However, we will check whether it is possible to release the codes of our key algorithms.

Very much looking forward to

**Comment by wduo** [comment]
> Hi, our code has already been deployed for commercial use, thus it was not allowed to be distributed.
> However, we will check whether it is possible to release the codes of our key algorithms.

Great job! I look forward to your release of core code samples for further research.
