### ISSUE TITLE
Please suggest cross camera tracking evaluation code

### ISSUE THREAD

**Issue by ssbilakeri** [GehenHe/TRACTA#17]

**Comment by GehenHe** [comment]
Hi, for the evaluation in terms of CLEAR metrics, including MOTA, MOTP, MODA, MODP, and IDF1 score, you can refer to [this](https://github.com/dendorferpatrick/MOTChallengeEvalKit). 
Just make sure the trajectories belonging to the same target under different cameras are assigned with the same ID label.

**Comment by lockxuan** [comment]
Hi, I write a python version of MCTA refers to http://www.mct2014.com/Evaluation.html.
Here is my repo: https://github.com/lockxuan/python-MCTA-Multiple-Camera-Tracking-Accuracy
Tell me if there's any question :)

**Comment by ssbilakeri** [comment]
Please tell me how you organize the dataset folders.
