### ISSUE TITLE
Unclear implementation of calculating similarity matrix S

### ISSUE THREAD

**Issue by reihig** [GehenHe/TRACTA#22]
Hi. Thank you for publishing your implementation. I would like to get an explanation of certain parts of your implementation.

I have read through your paper and the implementation and I could not understand that the implementation of calculating similarity matrix S is consistent with the description in the paper.

Specifically, in your paper, you explain that you used an algorithm from another paper for function φ_{***} but I could not find one in that paper that would correspond to the implementation in this repository. I was also unable to locate where the inner division of the value of φ is performed.

Could you please provide an explanation regarding these?

**Comment by lockxuan** [comment]
same question

**Comment by GehenHe** [comment]
Hi, thank you for your interest. The released code is a commercially-deployed version of our algorithm, which is designed for indoor MTMCT (such as supermarket MTMCT) with overlapping FOVs.  

In the overlapping FOV condition, we calculate the tracklet similarity using appearance and reference plane location, where the appearance similarity is a normalized cosine distance, and the location similarity is $e^{-d}$, where $d$ is the euclidean-distance between the two tracklets.
In the non-overlapping FOV condition, we calculate the tracklet similarity using appearance and camera topology.

The similarity calculation is not limited to the methods used in our algorithm, it is flexible to use different cues.
Hope this will be helpful.
