### ISSUE TITLE
The setting of the NLPR MCT dataset

### ISSUE THREAD

**Issue by lockxuan** [GehenHe/TRACTA#25]
Hi, thanks for the implementation code.

I'm trying to reproduce the result of the NLPRMCT dataset, and I met some problems.
1. How to get the similarity matrix? (same as #22)
- It seems that there is only SCT module and the rnmf algorithm module, but no the similarity measurement module.
2. How to set the parameters of the rnmf algorithm?
- I found some parameters in the rnmf algorithm that can be adjusted, I'm wondering how to change the parameters for the NLPRMCT dataset.
3. SCT algorithm with the non-overlapping camera scenario.
- It seems that the released code is implemented for the overlapping camera scenario, is the SCT algorithm for the non-overlapping camera scene a standard DEEPSORT algorithm?

Thank you!

**Comment by GehenHe** [comment]
Hi, thanks for your interest. The released code is a commercially-deployed version of our algorithm for overlapping MTMCT. The only difference between the non-overlapping and overlapping MTMCT is the calculation of the similarity matrix, which you can refer to Section III.D for more details.

**Comment by lockxuan** [comment]
Thank you,
is it possible to offer an example?
I'm trying the camera topology like the image below, however, it seems not perfect in my result.
![截圖 2022-07-25 下午6 42 47](https://user-images.githubusercontent.com/22294743/180759304-c9fbfa83-3c1c-4952-aa45-b68c453e4bb4.png)
![截圖 2022-07-25 下午6 42 58](https://user-images.githubusercontent.com/22294743/180759378-0aa9f524-4e32-41bf-bfdf-80844c5c71c1.png)
